# ¿Por qué NumPy y Pandas?
## ¿Por qué NumPy?
Es una librería enfocada al cálculo númerico y manejo de Arrays.

Es muy veloz, hasta 50 veces más rápido que usar una lista de Python o C.
Optimiza el almacenamiento en memoria.
Además, maneja distintos tipos de datos.
Es una librería muy poderosa, incluso en con ella se pueden crear redes neuronales desde cero.

## ¿Por qué Pandas?
Pandas está enfocada a la manipulación y análisis de datos.

Al estar construido sobre NumPy es veloz.
Requiere poco código para manipular los datos.
Soporta múltiples formatos de archivos.
Ordena los datos en una alienación inteligente.
Se pueden manejar grandes cantidades de datos, hacer analítica y crear dahsboards.


In [3]:
import numpy as np
import pandas as pd

### NumPy Array
El array es el principal objeto de la librería. Representa datos de manera estructurada y se puede acceder a ellos a traves del indexado, a un dato específico o un grupo de muchos datos específicos.

In [1]:
lista = [1, 2 , 3, 4, 5, 6, 7, 8, 9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
arr=np.array(lista)
type(arr)

numpy.ndarray

In [7]:
matriz=[[1,2,3], [4,5,6],[7,8,9]]
matriz=np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

El indexado nos permite acceder a los elementos de los array y matrices
Los elementos se empiezan a contar desde 0.

In [8]:
matriz[2]

array([7, 8, 9])

In [10]:
matriz[1,2]

6

Con ello es posible operar entre elementos

In [11]:
arr[0]+arr[7]

9

#### Slicing
Además se pueden acceder a partes en específico:

In [12]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [13]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [14]:
arr[::2]

array([1, 3, 5, 7, 9])

In [16]:
arr[-1]

9

In [17]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [21]:
arr[-5:-1]

array([5, 6, 7, 8])

Para el caso de las matrices sucede algo similar.
Para acceder a los valores a nivel de filas.

In [22]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [23]:
matriz[1:, 0:1]

array([[4],
       [7]])

Antes de todo para mantener que quede grabado qué librerías vamos a usar a lo largo de este archivo usamos:

In [3]:
import session_info

session_info.show()