# Tipos de datos
-----------------------------------------------------------------------------
Los arrays de NumPy solo pueden contener un tipo de dato, ya que esto es lo que le confiere las ventajas de la optimización de memoria.

Podemos conocer el tipo de datos del array consultando la propiedad .dtype.

In [1]:
import numpy as np

In [2]:

arr = np.array([1, 2, 3, 4])
arr.dtype

dtype('int32')


Si queremos usar otro tipo de dato lo podemos definir en la declaración del array.

In [3]:
arr = np.array([1, 2, 3, 4], dtype = 'float64')
arr.dtype

dtype('float64')

Ahora vemos que los valores están con punto decimal.

In [4]:
arr

array([1., 2., 3., 4.])

Si ya se tiene el array definido se usa el método .astype() para convertir el tipo de dato.


In [5]:
arr = np.array([1, 2, 3, 4])
arr = arr.astype(np.float64)
arr

array([1., 2., 3., 4.])

También se puede cambiar a tipo booleano recordando que los números diferentes de 0 se convierten en True.

In [6]:
arr = np.array([0, 1, 2, 3, 4])
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

También podemos convertir los datos en tipo string.

In [7]:
arr = np.array([0, 1, 2, 3, 4])
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S11')

De igual forma se puede pasar de string a numero.

In [8]:
arr = np.array(['0', '1', '2', '3', '4'])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)

Si un elemento no es de tipo número el método falla.

In [9]:
arr = np.array(['hola','0', '1', '2', '3', '4'])
arr = arr.astype(np.int8)
arr

ValueError: invalid literal for int() with base 10: 'hola'

linspace y arange, parecen iguales pero no lo son. En linspace en el tercer valor indicamos la cantidad de valores que iran en el intervalo , además nótese que linspace sí incluye el segundo valor que se coloca (10 en este ejemplo). En arange en el tercer valor indicamos de cuanto en cuanto irán saltanto, aquí NO toma el último valor (segundo valor que se da, 10 en este caso).

In [10]:
arrLins=np.linspace(0,10,5)
arrLins

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [11]:
arrArrange=np.arange(0,10,2.5)
arrArrange

array([0. , 2.5, 5. , 7.5])