# 🔀Creando arrays
Este métodode NumPy nos permite generar arrays sin definir previamente una lista.

In [1]:
import numpy as np

In [2]:
arr1=np.arange(0,10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Un tercer argumento permite definir un tamaño de paso.

In [4]:

arr2=np.arange(0,20,2)
arr2


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

p.zeros() nos permite definir estructuras o esquemas.

In [7]:
arr3=np.zeros(3)
print(arr3)
arr4=np.zeros((10,5))
arr4

[0. 0. 0.]


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

De iugal forma tenemos np.ones()

In [9]:

arr5=np.ones(3)
print(arr5)
arr7=np.ones((4,4))
arr7

[1. 1. 1.]


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])


np.linspace() permite generar una arrary definiendo un incio, un final y cuantas divisiones tendrá.


In [10]:

arr8=np.linspace(0, 100 , 10)
arr8


array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

También podemos crear una matriz con una diagonal de 1 y el resto de 9.


In [11]:
arr9=np.eye(4)
arr9


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])


Otra metódo importante es generar números aleatorios.


In [18]:
rdm=np.random.rand()
rdm

0.5571020537824302

También se pueden generar vectores.


In [23]:

arr10=np.random.rand(4)
arr10


array([0.63964611, 0.35457534, 0.36914634, 0.95537794])

Y a su vez generar matrices.


In [24]:
arr11=np.random.rand(4,4)
arr11

array([[0.29167316, 0.29604477, 0.38816801, 0.42898607],
       [0.13357566, 0.12372622, 0.6822783 , 0.89856414],
       [0.9727398 , 0.44740497, 0.41112548, 0.16258022],
       [0.25762896, 0.57368677, 0.69018853, 0.70090417]])

NumPy nos permite tambien generar números enteros.
En este caso números enteros entre el 1 y 14

In [ ]:

arr12=np.random.randint(1,15)
arr12


También podemos llevarlos a una estructura definida.


In [27]:

arr13=np.random.randint(1,15, (3,3))
arr13

array([[10,  6,  7],
       [ 4, 12, 11],
       [ 4,  3,  1]])

Para tener una matriz con un numero predeterminado

In [30]:
arr14= np.full((3,3),7)
arr14

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

Random choice genera un numeros aleatorios de un set de numeros definidos.

In [31]:
arr15 = np.random.choice([1,3,5,7,9], (3, 5))
print(arr15) 

[[3 1 3 5 5]
 [9 9 3 1 5]
 [7 9 7 5 7]]


# BONUS
## Shape y Reshape

Shape me indica la forma del arreglo
Reshape transforma el arreglo mientras se mantengan los elementos.


In [33]:
arr = np.random.randint(1,10,(3,2))
arr.shape



(3, 2)

In [39]:
arr

array([[9, 7],
       [1, 5],
       [1, 3]])

In [34]:
arr.reshape(1,6)

array([[9, 7, 1, 5, 1, 3]])

In [35]:
arr.reshape(2,3)

array([[9, 7, 1],
       [5, 1, 3]])

In [36]:

np.reshape(arr,(1,6))

array([[9, 7, 1, 5, 1, 3]])


Se puede hacer un reshape como lo haría C.


In [37]:

np.reshape(arr,(2,3), 'C')


array([[9, 7, 1],
       [5, 1, 3]])


También se puede hacer reshape a como lo haría Fortran.


In [38]:

np.reshape(arr,(2,3), 'F')


array([[9, 1, 5],
       [1, 7, 3]])


Además existe la opción de hacer reshape según como esté optimizado nuestro computador. En este caso es como en C.


In [40]:

np.reshape(arr,(2,3), 'A')

array([[9, 7, 1],
       [5, 1, 3]])

Si en el .reshape indicamos -1 como una de las dimensiones, esta será calculada automáticamente por numpy.

In [41]:
arr = np.random.randint(1,10,(4,6))
arr

array([[6, 4, 1, 9, 5, 6],
       [2, 7, 4, 9, 5, 6],
       [1, 5, 7, 3, 5, 5],
       [8, 8, 7, 6, 2, 5]])

In [42]:
arr.reshape(2,-1)

array([[6, 4, 1, 9, 5, 6, 2, 7, 4, 9, 5, 6],
       [1, 5, 7, 3, 5, 5, 8, 8, 7, 6, 2, 5]])

En este caso -1 vale por 12

Aplica para más dimensiones …

In [43]:
arr.reshape(3,2,-1)

array([[[6, 4, 1, 9],
        [5, 6, 2, 7]],

       [[4, 9, 5, 6],
        [1, 5, 7, 3]],

       [[5, 5, 8, 8],
        [7, 6, 2, 5]]])

Y en este caso -1 vale por 4.