### 🧮Funciones principales de NumPy


In [1]:
import numpy as np

In [6]:

arr = np.random.randint(1, 30, 15)
matriz = arr.reshape(3,5)
matriz

array([[19, 12, 17,  1, 23],
       [10, 21, 15, 15,  6],
       [25, 14, 10,  3,  1]])

In [7]:
arr

array([19, 12, 17,  1, 23, 10, 21, 15, 15,  6, 25, 14, 10,  3,  1])

In [8]:
arr.max() 


25

In [9]:
matriz.max()


25

Podemos regresar los máximos de cada fila o columna especificando el eje.


In [12]:
matriz

array([[19, 12, 17,  1, 23],
       [10, 21, 15, 15,  6],
       [25, 14, 10,  3,  1]])

In [11]:

matriz.max(1)


array([23, 21, 25])

In [10]:
matriz.max(0)

array([25, 21, 17, 15, 23])

Tambien tenemos .argmax() que nos devuelve la posición del elemento


In [13]:
arr.argmax() 

10

In [14]:
matriz.argmax(0) 

array([2, 1, 0, 1, 0], dtype=int64)


De forma análoga tenemos .min()


In [15]:

arr.min() 


1

In [16]:
arr.argmin() 


3

In [17]:
matriz.min(0) 


array([10, 12, 10,  1,  1])

In [18]:

matriz.argmin(1)


array([3, 4, 4], dtype=int64)

Podemos saber la diferencia de valor más bajo con el más alto.


In [19]:

arr.ptp()


24

In [20]:
matriz.ptp(0)  


array([15,  9,  7, 14, 22])


Para hacer análisis estádistico se tienen la siguientes funciones.



Ordenar los elementos:


In [22]:
arr

array([ 1,  1,  3,  6, 10, 10, 12, 14, 15, 15, 17, 19, 21, 23, 25])

In [21]:

arr.sort()


Sin embargo, si no se quiere alteral el array original, es mejor usar *np.sort(array)*



Obtener un percentil:


In [24]:

np.percentile(arr, 50) 


14.0

Mediana:


In [25]:

np.median(arr) 


14.0


Desviación estándar:


In [26]:


np.std(arr) 


7.413501197140255

Varianza:


In [27]:

np.var(arr) 


54.959999999999994

Promedio:


In [28]:

np.mean(arr) 


12.8


Lo mismo aplica para las matrices.


In [29]:

np.median(matriz, 1)


array([ 3., 14., 21.])

In [30]:

np.median(matriz, 0)


array([10., 12., 14., 15., 15.])

Se pueden unir dos arrays por medio de la concatenación


In [31]:

a = np.array([[1,2], [3,4]])
b= np.array([5, 6])
np.concatenate((a,b), axis = 0)
# Saldrá un error

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)



El error anterior es debido a a tiene 2 dimensiones mientras que b tiene 1.


In [32]:

print(a.ndim)
b.ndim


2


1

In [33]:
b = np.expand_dims(b, axis = 0)
np.concatenate((a,b), axis = 0)


array([[1, 2],
       [3, 4],
       [5, 6]])


De igual forma podemos agregarlo en el otro eje


In [34]:

np.concatenate((a,b), axis = 1)
#Saldrá otro error


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1


Como b es una fila y no una columna, no se puede concatenar a menos que se aplique la transpuesta ( *b.T* ) o se haga un resize


In [35]:

np.concatenate((a,b.T), axis = 1)


array([[1, 2, 5],
       [3, 4, 6]])

## 📝Copy
.copy() nos permite copiar un array de NumPy en otra variable de tal forma que al modificar el nuevo array los cambios no se vean reflejados en array original.


In [36]:


arr = np.arange(0, 11)
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:

arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [38]:
trozo_de_arr = arr[0:6]
trozo_de_arr[:] = 0
trozo_de_arr


array([0, 0, 0, 0, 0, 0])

Se han modificado los datos del array original porque seguía haciendo referencia a esa variable.


In [39]:

arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [40]:
arr_copy = arr.copy()
arr_copy[:] = 100
arr_copy 

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [41]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])