# ✅Condiciones
Las condiciones nos permiten hacer consultas más específicas.


In [1]:
import numpy as np

In [3]:

arr = np.linspace(1,10,10, dtype = 'int8')
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

Regresa un array de booleanos donde la condiciones se cumple.


In [4]:

indices_cond = arr > 5
indices_cond


array([False, False, False, False, False,  True,  True,  True,  True,
        True])

Regresa los valores para donde la condiciones True.


In [7]:

arr[indices_cond]


array([ 6,  7,  8,  9, 10], dtype=int8)

Se pueden agregar múltiples condiciones.


In [8]:

arr[(arr > 5) & (arr < 9)]


array([6, 7, 8], dtype=int8)

De igual forma modificar los valores que cumplan la condición.


In [13]:
arrCopy=np.copy(arr)
arrCopy[arr > 5] = 99
arrCopy


array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

Otra función muy útil de numpy también es np.where(condición, valor sí, valor si la condicion no se cumple), ejemplo:

In [14]:
matriz = np.array([[19,  4, 43],
        [ 8, 96, 80],
        [ 6, 99, 35]])

np.where(matriz > 50, 0, 1)

array([[1, 1, 1],
       [1, 0, 0],
       [1, 0, 1]])

### Ejemplos

In [17]:
arr = np.arange(1,51, dtype='int8')
print(arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [18]:
print(arr[(arr % 2 == 0)]) #Pares


[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


In [19]:
print(arr[(arr % 2 != 0)]) #Impares


[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [20]:
print(arr[(arr % 3 == 0)]) #Multiplos de 3

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]
