# 🔣Operaciones
Existen diferentes operaciones que se pueden usar para los arrays de NumPy.


In [1]:
import numpy as np

In [2]:

lista = [1,2]
lista 


[1, 2]

Una lista de Python entiende que quieres duplicar los datos. Cosa que no buscamos.


In [4]:

lista * 2


[1, 2, 1, 2]

In [5]:
arr = np.arange(0,10)
arr2 = arr.copy()
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Ahora multiplicamos por un escalar:


In [6]:

arr * 2


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Operación suma de escalar:


In [7]:

arr + 2


array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

División con un escalar
Como en este caso la primera posición del array es 0, muestra un error pero no detiene el proceso.


In [8]:


1/arr


C:\Users\dumss\AppData\Local\Temp\ipykernel_2164\3148478060.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

Elevar a un escalar:


In [9]:

arr**2


array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

Sumar dos arrays de igual dimensiones las hace elemento por elemento:


In [10]:

arr + arr2


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Lo mismo aplica para matrices.


In [11]:

matriz = arr.reshape(2,5)
matriz2 = matriz.copy()
matriz


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
matriz - matriz2


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])


Una operación importante es la de punto por punto, aquí dos formas de hacerla:


In [13]:

np.matmul(matriz, matriz2.T)


array([[ 30,  80],
       [ 80, 255]])

In [14]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])

También existe el operador *np.unique*, con esta operación quitaremos los valores repetidos de nuestro array. Lo mas increíble es que se pueden hacer algunas operaciones extras como lo son “Sabes cuántas veces se repiten dichos datos” 

In [15]:
arr=np.array([11,11,12,13,13,14,14,14,14,15,15,16,17,18,19,19,19])
arrCopy=arr.copy
arr

array([11, 11, 12, 13, 13, 14, 14, 14, 14, 15, 15, 16, 17, 18, 19, 19, 19])

In [16]:
uniqueEj=np.unique(arr)
uniqueEj

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
uniqueEj,ocurrence=np.unique(arr, return_counts=True)
ocurrence


array([2, 1, 2, 4, 2, 1, 1, 1, 3], dtype=int64)

In [18]:
uniqueGeneral=np.unique(arr, return_counts=True, return_index=True,return_inverse=True)
uniqueGeneral

(array([11, 12, 13, 14, 15, 16, 17, 18, 19]),
 array([ 0,  2,  3,  5,  9, 11, 12, 13, 14], dtype=int64),
 array([0, 0, 1, 2, 2, 3, 3, 3, 3, 4, 4, 5, 6, 7, 8, 8, 8], dtype=int64),
 array([2, 1, 2, 4, 2, 1, 1, 1, 3], dtype=int64))